export HOST="stackbuilders@staging.stackbuilders.com"
export REPOSITORY="git@github.com:stackbuilders/tutorials.git"
export REVISION="origin/tutorials"
export BUILD_SCRIPT="deploy/stack-tutorials-build.sh"
export RESTART_COMMAND="pwd"
