-- File auto generated by purescript-bridge! --
module Types where

import Prim (Array, String)

import Data.Generic (class Generic)


data Scientist =
    Scientist {
      sNames :: Array String
    , sPhotoUrl :: String
    }

derive instance genericScientist :: Generic Scientist

